name: Build Zip for Testing

on:
  push:
    branches:
      - '**'
    paths:
      - 'calibre-plugin/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - '**'
    paths:
      - 'calibre-plugin/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 1
      - name: Install requirements for linting
        run: pip install -r requirements-dev.txt
      - name: Lint
        run: sh lint.sh
      # - name: Run tests
      # run: python -m unittest -v tests
      - name: Install gtext
        run: sudo apt-get -y install gettext
      - name: Generate commit.txt and build .mo files
        run: |
          echo "$GITHUB_SHA" > calibre-plugin/commit.txt
          cd .github/workflows
          sh build_translations.sh
      - name: Shorten GITHUB_SHA
        run: echo "github_short_sha=${GITHUB_SHA::7}" >> $GITHUB_ENV
      - name: Upload plugin
        uses: actions/upload-artifact@v3
        with:
          name: overdrive-libby-plugin-${{ env.github_short_sha }}
          path: |
            calibre-plugin/
            !calibre-plugin/translations/*.po
            !calibre-plugin/translations/*.pot
